version: '3.8'
services:
    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: driverjobs-dev
            POSTGRES_USER: filip
            POSTGRES_PASSWORD: filip
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
